name: sotoru
description: Go-out swipes for Tbilisi
publish_to: "none"
version: 0.8.1+81

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.9.0
  geolocator: ^12.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.2
  image_picker: ^1.1.2
  video_player: ^2.8.6
  path_provider: ^2.1.4
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
